[project]
name = "branch-probe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.1.0",
    "jupyter>=1.1.1",
    "torch>=2.10.0",
    "tqdm>=4.67.3",
    "transformer-lens>=2.17.0",
]
